name: QAQC catwalk data
on:
   push:
      branches: [ fcre-catwalk-data ]
      #paths: 
      #- 'fcre-waterquality.csv'
   workflow_dispatch:

jobs:
  qaqc_run:
     runs-on: ubuntu-latest
     container:
      image: rocker/tidyverse:latest
      working-directory: /github/workspace
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
         with:
           ref: fcre-catwalk-data
           fetch-depth: 1
       - name: Run QAQC script
         run:  | 
           R -e 'install.packages(c("EDIutils","xml2","here"))'
           Rscript R/QAQC_workflow.R
       - name: Checkout qaqc-data branch
         uses: actions/checkout@v3
         with:
           ref: qaqc-data
       - name: Commit files
         run: |
            git config --global --add safe.directory $GITHUB_WORKSPACE
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add fcre-waterquality_L1.csv
            git commit -m "Updating QAQC file" || echo "No changes to commit"
            git push -u origin qaqc-data || echo "No changes to commit"
